/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nrodas.archivosp1.interfazgrafica;

import com.nrodas.archivosp1.apoyo.Conversor;
import com.nrodas.archivosp1.apoyo.LlenadorTabla;
import com.nrodas.archivosp1.entidades.Reporte;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;

/**
 * Clase que maneja el penel 1 de administracion
 *
 * @author lroda
 */
public class Admin_Pnl1 extends javax.swing.JPanel {

    /**
     * Atributos
     */
    Reporte reporte;

    /**
     * Constructor
     */
    public Admin_Pnl1() {
        initComponents();
        reporte = new Reporte();
        this.jPanelMuestra.setVisible(false);
        this.jComboBoxSucursal.setVisible(false);
        this.setSize(980, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelT1 = new javax.swing.JLabel();
        jScrollPaneReportes = new javax.swing.JScrollPane();
        jListReportes = new javax.swing.JList<>();
        jPanelMuestra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSucursal = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelT1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelT1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelT1.setText("Escoge el reporte a mostrar:");
        add(jLabelT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, -1));

        jScrollPaneReportes.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneReportes.setBorder(null);
        jScrollPaneReportes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jListReportes.setBackground(new java.awt.Color(255, 255, 255));
        jListReportes.setFont(new java.awt.Font("SansSerif", 0, 21)); // NOI18N
        jListReportes.setForeground(new java.awt.Color(0, 0, 0));
        jListReportes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Top 10 clientes que generan más ganancias", "Top 3 sucursales con más ventas", "Top 3 sucursales con más ingresos", "Top 3 empleados con más ventas", "Top 3 empleados con más ingresos", "Top 10 productos más vendidos", "Top 10 productos que generan más ingresos", "Top 5 productos más vendidos por sucursal", "Top 5 productos que generan más ingresos por sucursal" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListReportes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListReportes.setSelectionBackground(new java.awt.Color(216, 216, 216));
        jListReportes.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jListReportes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListReportesValueChanged(evt);
            }
        });
        jScrollPaneReportes.setViewportView(jListReportes);

        add(jScrollPaneReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 540, 150));

        jPanelMuestra.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMuestra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelMuestra.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 251));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Top: ");
        jPanelMuestra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        jComboBoxSucursal.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxSucursal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBoxSucursal.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una sucursal...", "Sucursal Central", "Sucursal Norte", "Sucursal Sur" }));
        jComboBoxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSucursalActionPerformed(evt);
            }
        });
        jPanelMuestra.add(jComboBoxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 160, 40));

        add(jPanelMuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 850, 320));
    }// </editor-fold>//GEN-END:initComponents

    /*Metodo relacionado con la seleccion en la lista*/

    private void jListReportesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListReportesValueChanged
        int item = this.jListReportes.getSelectedIndex();
        if (!this.jPanelMuestra.isVisible()) {
            this.jPanelMuestra.setVisible(true);
        }
        if (this.jComboBoxSucursal.isVisible()) {
            this.jComboBoxSucursal.setVisible(false);
        }
        switch (item) {
            case 0:
                reporte.buscarClientesGanancias();
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Ganancias", "NIT", "Nombre del Cliente"});
                LlenadorTabla.llenarTabla(jTable1, reporte.getLb());
                break;
            case 1:
                reporte.calcularVentasPorSucursal();
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Ventas Totales", "Sucursal"});
                LlenadorTabla.llenarTabla(jTable1, reporte.getLb());

                break;
            case 2:
                reporte.calcularIngresosPorSucursal();
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Ingresos Totales", "Sucursal"});
                LlenadorTabla.llenarTabla(jTable1, reporte.getLb());

                break;
            case 3:
                reporte.contarEmpleadosVentas();
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Ventas Totales", "Codigo Empleado", "Nombre Empleado", "Sucursal"});
                LlenadorTabla.llenarTabla(jTable1, reporte.getLb());
                break;
            case 4:
                reporte.sumarEmpleadosIngresos();
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Ingresos Totales", "Codigo Empleado", "Nombre Empleado", "Sucursal"});
                LlenadorTabla.llenarTabla(jTable1, reporte.getLb());
                break;
            case 5:
                reporte.buscarProductosVendidos();
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Codigo del Prodcuto", "Descripcion", "Cantidad Vendida"});
                LlenadorTabla.llenarTabla(jTable1, reporte.getLb());
                break;
            case 6:
                reporte.contarProductosIngresos();
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Codigo del Prodcuto", "Descripcion", "Total Ingresos"});
                LlenadorTabla.llenarTabla(jTable1, reporte.getLb());
                break;
            case 7:
                this.jComboBoxSucursal.setVisible(true);
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Codigo del Prodcuto", "Descripcion", "Cantidad Vendida"});
                break;
            case 8:
                this.jComboBoxSucursal.setVisible(true);
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Codigo del Prodcuto", "Descripcion", "Ingresos Totales"});
                break;
        }
    }//GEN-LAST:event_jListReportesValueChanged

    private void jComboBoxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSucursalActionPerformed
        String sucursalelegida = String.valueOf(this.jComboBoxSucursal.getSelectedItem()); //Obtiene el iten en forma de string
        if (!sucursalelegida.trim().equals("Elija una sucursal...")) { //Valida que no sea la opcion por defecto
            int sucursal = Conversor.determinarSucursal(sucursalelegida); //Obtiene el id de la sucursal
            if (this.jListReportes.getSelectedIndex() == 7) { //Crea los respectivos reportes para la opcion 7
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Codigo del Prodcuto", "Descripcion", "Cantidad Vendida"});
                reporte.buscarTop5Productos(sucursal);
                LlenadorTabla.llenarTabla(jTable1, reporte.getLb());
            } else if (this.jListReportes.getSelectedIndex() == 8) { //Crea los respectivos reportes para la opcion 8
                LlenadorTabla.cambiarEncabezado(jTable1, new String[]{"No.", "Codigo del Prodcuto", "Descripcion", "Ingresos Totales"});
                reporte.buscarTop5ProductosIng(sucursal);
                LlenadorTabla.llenarTabla(jTable1, reporte.getLb());
            }
        }
    }//GEN-LAST:event_jComboBoxSucursalActionPerformed

    /**
     * Variable declaradas por netbeans
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JList<String> jListReportes;
    private javax.swing.JPanel jPanelMuestra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneReportes;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
