/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nrodas.archivosp1.interfazgrafica;

import com.nrodas.archivosp1.apoyo.Contrasenia;
import com.nrodas.archivosp1.apoyo.Conversor;
import com.nrodas.archivosp1.entidades.Empleado;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 * Clase que maneja el penel 2 de administracion
 * @author lroda
 */
public class Admin_Pnl2 extends javax.swing.JPanel {

    /**
     * Atributos
     */
    private Empleado emp;

    /**
     * Constructor
     */
    public Admin_Pnl2() {
        initComponents();
        emp = new Empleado();
        this.setSize(980, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelT1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodEmp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelPsswrd = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelRol = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jLabelSucursal = new javax.swing.JLabel();
        jComboBoxSucursal = new javax.swing.JComboBox<>();
        jPanelBtnCont = new javax.swing.JPanel();
        jLabelBtnCont = new javax.swing.JLabel();
        jLabelReco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelT1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabelT1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelT1.setText("Ingresa los datos del nuevo Empleado");
        add(jLabelT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 670, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo de Empleado: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 250, -1));

        jTextFieldCodEmp.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodEmp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldCodEmp.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCodEmp.setBorder(null);
        jTextFieldCodEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodEmpKeyTyped(evt);
            }
        });
        add(jTextFieldCodEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 150, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 150, 10));

        jLabelPsswrd.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPsswrd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPsswrd.setText("Password: ");
        add(jLabelPsswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 130, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 140, 10));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(null);
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 159, 140, 30));

        jLabelNombre.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setText("Nombre: ");
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 110, -1));

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 400, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 400, 10));

        jLabelRol.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelRol.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRol.setText("Rol: ");
        add(jLabelRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 60, -1));

        jComboBoxRol.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxRol.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxRol.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta", "Inventario", "Bodega", "Administración" }));
        jComboBoxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRolActionPerformed(evt);
            }
        });
        add(jComboBoxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 100, 30));

        jLabelSucursal.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelSucursal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSucursal.setText("Instalacion: ");
        add(jLabelSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 140, -1));

        jComboBoxSucursal.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxSucursal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxSucursal.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intalación" }));
        jComboBoxSucursal.setEnabled(false);
        jComboBoxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSucursalActionPerformed(evt);
            }
        });
        add(jComboBoxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 130, 30));

        jPanelBtnCont.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBtnCont.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelBtnCont.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnCont.setText("Contratar");
        jLabelBtnCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnContMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnContMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnContMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnContLayout = new javax.swing.GroupLayout(jPanelBtnCont);
        jPanelBtnCont.setLayout(jPanelBtnContLayout);
        jPanelBtnContLayout.setHorizontalGroup(
            jPanelBtnContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnCont, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanelBtnContLayout.setVerticalGroup(
            jPanelBtnContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnCont, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanelBtnCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 150, 40));

        jLabelReco.setForeground(new java.awt.Color(0, 0, 0));
        jLabelReco.setText("Escribe una segura");
        add(jLabelReco, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 140, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Salario: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 299, 120, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 120, 10));
    }// </editor-fold>//GEN-END:initComponents

    /*
    *Eventos Relacionados con los botones
     */
    private void jLabelBtnContMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnContMouseEntered
        this.jPanelBtnCont.setBackground(new Color(152, 155, 158));
    }//GEN-LAST:event_jLabelBtnContMouseEntered

    private void jLabelBtnContMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnContMouseExited
        this.jPanelBtnCont.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBtnContMouseExited

    /*
    *Metodo relacionados con los JtextFields
     */

    private void jTextFieldCodEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodEmpKeyTyped
        int key = evt.getKeyChar();
        if (!(key >= 48 && key <= 57)) {
            evt.consume();
        }
        if (this.jTextFieldCodEmp.getText().length() > 9) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldCodEmpKeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        int key = evt.getKeyChar();
        if (!(key <= 48) && !(key >= 57)) {
            evt.consume();
        }
        if (this.jTextFieldNombre.getText().length() > 49) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    /*
    Evento Relacionado con la insercion de empleados
     */

    private void jLabelBtnContMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnContMouseClicked
        String codigoEmp = this.jTextFieldCodEmp.getText();
        String pass = Contrasenia.hashearContrasenia(String.valueOf(this.jPasswordField1.getPassword()));
        String sueldo = this.jTextField1.getText();
        String nombre = this.jTextFieldNombre.getText();
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (!(codigoEmp.isBlank()) && !(pass.isBlank()) && !(nombre.isBlank()) && !(sueldo.isBlank())) {
            this.emp.setNombreEmpleado(nombre);
            this.emp.setContrasenia(pass);
            this.emp.setIdUsuario(Long.valueOf(codigoEmp));
            this.emp.setSalario(Double.valueOf(sueldo));
            Administracion admi = (Administracion)SwingUtilities.getWindowAncestor(this);
            if (this.emp.agregarEmpleado()) {
                ShowMsg msg = new ShowMsg(frame, true, "Empleado Agregado Con Exito");
                admi.repintarEmpleado();
            }
        } else {
            ShowMsg msg = new ShowMsg(frame, true, "Aun no has llenado todos los campos");
        }
    }//GEN-LAST:event_jLabelBtnContMouseClicked

    /*
    * Metodos relacionados con los JComboBox
    */
    private void jComboBoxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRolActionPerformed
        int rol = this.jComboBoxRol.getSelectedIndex();
        switch (rol) {
            case 0:
                this.emp.setRol(1);
                this.jComboBoxSucursal.removeAllItems();
                this.jComboBoxSucursal.addItem("Sucursal Central");
                this.jComboBoxSucursal.addItem("Sucursal Norte");
                this.jComboBoxSucursal.addItem("Sucursal Sur");
                break;
            case 1:
                this.emp.setRol(2);
                this.jComboBoxSucursal.removeAllItems();
                this.jComboBoxSucursal.addItem("Sucursal Central");
                this.jComboBoxSucursal.addItem("Sucursal Norte");
                this.jComboBoxSucursal.addItem("Sucursal Sur");
                break;
            case 2:
                this.emp.setRol(3);
                this.jComboBoxSucursal.removeAllItems();
                this.jComboBoxSucursal.addItem("Bodega");
                break;
            case 3:
                this.emp.setRol(4);
                this.jComboBoxSucursal.removeAllItems();
                this.jComboBoxSucursal.addItem("All");
                break;
        }
        if (!this.jComboBoxSucursal.isEnabled()) {
            this.jComboBoxSucursal.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxRolActionPerformed

    private void jComboBoxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSucursalActionPerformed
        String opcion = String.valueOf(this.jComboBoxSucursal.getSelectedItem()).trim();
        switch (opcion) {
            case "Sucursal Centra":
                this.emp.setSucursal(3);
                break;
            case "Sucursal Norte":
                this.emp.setSucursal(4);
                break;
            case "Sucursal Sur":
                this.emp.setSucursal(5);
                break;
            case "Bodega":
                this.emp.setSucursal(2);
                break;
            case "All":
                this.emp.setSucursal(1);
                break;
        }
{
            
        }
    }//GEN-LAST:event_jComboBoxSucursalActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == '.')) {
            evt.consume();
        }
        if (c == '.' && this.jTextField1.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JComboBox<String> jComboBoxSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBtnCont;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPsswrd;
    private javax.swing.JLabel jLabelReco;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JPanel jPanelBtnCont;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCodEmp;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
