/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nrodas.archivosp1.interfazgrafica;

import com.nrodas.archivosp1.apoyo.LlenadorTabla;
import com.nrodas.archivosp1.entidades.Producto;
import com.nrodas.archivosp1.entidades.Reporte;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * Clase que maneja el panel 2 de bodega
 * @author lroda
 */
public class Bod_Pnl2 extends javax.swing.JPanel {

    /**
     * Atributos
     */
    private Producto producto;

    /**
     * Constructor
     */
    public Bod_Pnl2() {
        initComponents();
        Reporte reporte = new Reporte();
        LlenadorTabla.cambiarEncabezado(this.jTableUpdate, new String[]{"Codigo Producto", "Descripcion", "Cantidad", "Precio Unitario"});
        reporte.retornarProductosInventario(1);
        LlenadorTabla.llenarTablaInventario(this.jTableUpdate, reporte.getLb());
        this.setSize(980, 650);
        this.jPanelForm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelT1 = new javax.swing.JLabel();
        jLabelCodigoPdt = new javax.swing.JLabel();
        jTextFieldCodigoPdt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelBtnBuscar = new javax.swing.JPanel();
        jLabelBtnBuscar = new javax.swing.JLabel();
        jPanelForm = new javax.swing.JPanel();
        jLabelDesc = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelCantidad = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jLabelPrezio = new javax.swing.JLabel();
        jTextFieldPrezio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelBtnModificar = new javax.swing.JPanel();
        jLabelBtnModificar = new javax.swing.JLabel();
        jPanelFondoTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUpdate = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(980, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelT1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelT1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelT1.setText("Modifica los productos");
        add(jLabelT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 470, -1));

        jLabelCodigoPdt.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelCodigoPdt.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodigoPdt.setText("Busca el producto: ");
        add(jLabelCodigoPdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 240, -1));

        jTextFieldCodigoPdt.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoPdt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldCodigoPdt.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCodigoPdt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigoPdt.setBorder(null);
        jTextFieldCodigoPdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoPdtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoPdtKeyTyped(evt);
            }
        });
        add(jTextFieldCodigoPdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 180, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 180, 10));

        jPanelBtnBuscar.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBtnBuscar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuscarPdt.png"))); // NOI18N
        jLabelBtnBuscar.setText("Buscar");
        jLabelBtnBuscar.setEnabled(false);
        jLabelBtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnBuscarLayout = new javax.swing.GroupLayout(jPanelBtnBuscar);
        jPanelBtnBuscar.setLayout(jPanelBtnBuscarLayout);
        jPanelBtnBuscarLayout.setHorizontalGroup(
            jPanelBtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanelBtnBuscarLayout.setVerticalGroup(
            jPanelBtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(jPanelBtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 140, 30));

        jPanelForm.setBackground(new java.awt.Color(255, 255, 255));
        jPanelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDesc.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelDesc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDesc.setText("Descripcion: ");
        jPanelForm.add(jLabelDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        jTextFieldDesc.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDesc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldDesc.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDesc.setBorder(null);
        jTextFieldDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDescKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescKeyTyped(evt);
            }
        });
        jPanelForm.add(jTextFieldDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 9, 410, 30));
        jPanelForm.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 410, 10));

        jLabelCantidad.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantidad.setText("Cantidad: ");
        jPanelForm.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 130, -1));

        jSpinnerCantidad.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jSpinnerCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCantidadStateChanged(evt);
            }
        });
        jPanelForm.add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 70, 30));

        jLabelPrezio.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelPrezio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrezio.setText("Precio: ");
        jPanelForm.add(jLabelPrezio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 100, -1));

        jTextFieldPrezio.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPrezio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldPrezio.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPrezio.setBorder(null);
        jTextFieldPrezio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrezioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrezioKeyTyped(evt);
            }
        });
        jPanelForm.add(jTextFieldPrezio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 30));
        jPanelForm.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, 10));

        jPanelBtnModificar.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBtnModificar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModPdt.png"))); // NOI18N
        jLabelBtnModificar.setText("Modificar");
        jLabelBtnModificar.setEnabled(false);
        jLabelBtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnModificarLayout = new javax.swing.GroupLayout(jPanelBtnModificar);
        jPanelBtnModificar.setLayout(jPanelBtnModificarLayout);
        jPanelBtnModificarLayout.setHorizontalGroup(
            jPanelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanelBtnModificarLayout.setVerticalGroup(
            jPanelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelForm.add(jPanelBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 140, 40));

        add(jPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 880, 120));

        jPanelFondoTabla.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUpdate);

        javax.swing.GroupLayout jPanelFondoTablaLayout = new javax.swing.GroupLayout(jPanelFondoTabla);
        jPanelFondoTabla.setLayout(jPanelFondoTablaLayout);
        jPanelFondoTablaLayout.setHorizontalGroup(
            jPanelFondoTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanelFondoTablaLayout.setVerticalGroup(
            jPanelFondoTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        add(jPanelFondoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 880, 310));
    }// </editor-fold>//GEN-END:initComponents

    /*
        Metodos relacionados con el mouse y los botones
     */
    private void jLabelBtnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnBuscarMouseEntered
        if (this.jLabelBtnBuscar.isEnabled()) {
            this.jPanelBtnBuscar.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelBtnBuscarMouseEntered

    private void jLabelBtnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnBuscarMouseExited
        this.jPanelBtnBuscar.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBtnBuscarMouseExited

    private void jLabelBtnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnModificarMouseEntered
        if (this.jLabelBtnModificar.isEnabled()) {
            this.jPanelBtnModificar.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelBtnModificarMouseEntered

    private void jLabelBtnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnModificarMouseExited
        this.jPanelBtnModificar.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBtnModificarMouseExited

    /*
        Eventos relacionados con los JtextFields
     */
    private void jTextFieldCodigoPdtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPdtKeyTyped
        if (this.jTextFieldCodigoPdt.getText().length() > 11) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldCodigoPdtKeyTyped

    private void jTextFieldCodigoPdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPdtKeyReleased
        if (this.jTextFieldCodigoPdt.getText().isBlank()) {
            this.jLabelBtnBuscar.setEnabled(false);
        } else {
            this.jLabelBtnBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldCodigoPdtKeyReleased

    /*
        Evento click del boton de buscar
     */
    private void jLabelBtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnBuscarMouseClicked
        if (this.jLabelBtnBuscar.isEnabled()) {
            producto = new Producto();
            boolean encontrado = producto.buscarProducto(this.jTextFieldCodigoPdt.getText(), 1);
            if (encontrado) {
                this.jTextFieldDesc.setText(producto.getDescripcionProducto());
                this.jTextFieldPrezio.setText(producto.getPrecioUnitario() + "");
                this.jSpinnerCantidad.setValue((Object) producto.getCantidad());
                this.jPanelForm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "El producto que ingresas no existe");
            }
        }
    }//GEN-LAST:event_jLabelBtnBuscarMouseClicked

    /*
        Metodo relacionados con los JtextFields del form
     */
    private void jTextFieldDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescKeyTyped
        if (this.jTextFieldDesc.getText().length() > 99) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldDescKeyTyped

    private void jTextFieldDescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_BACK_SPACE || key == KeyEvent.VK_DELETE) {
            if (!this.jLabelBtnModificar.isEnabled()) {
                this.jLabelBtnModificar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jTextFieldDescKeyReleased

    private void jTextFieldPrezioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrezioKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == '.')) {
            evt.consume();
        }
        if (c == '.' && this.jTextFieldPrezio.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrezioKeyTyped

    private void jTextFieldPrezioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrezioKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_BACK_SPACE || key == KeyEvent.VK_DELETE) {
            if (!this.jLabelBtnModificar.isEnabled()) {
                this.jLabelBtnModificar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jTextFieldPrezioKeyReleased

    private void jSpinnerCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCantidadStateChanged
        if (!this.jLabelBtnModificar.isEnabled()) {
            this.jLabelBtnModificar.setEnabled(true);
        }
    }//GEN-LAST:event_jSpinnerCantidadStateChanged

    /*
        Metodo de click para modificar el producto
     */
    private void jLabelBtnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnModificarMouseClicked
        if (this.jLabelBtnModificar.isEnabled()) {
            boolean actualizarDesc = this.producto.acutalizatDesc(this.jTextFieldDesc.getText().trim());
            boolean actualizarPrec = this.producto.actualizarPrezio(Double.valueOf(this.jTextFieldPrezio.getText().trim()));
            boolean actualizarStock = this.producto.actualizarStock(this.producto.getCodigoProducto(), this.producto.getInventario(),
                    Integer.valueOf(String.valueOf(this.jSpinnerCantidad.getValue())));
            if (actualizarDesc && actualizarPrec && actualizarStock) {
                JOptionPane.showMessageDialog(null, "Producto Actualizado");
                this.jPanelForm.setVisible(false);
                Bodega bod = (Bodega)SwingUtilities.getWindowAncestor(this);
                bod.repintarModPdt();
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error al intentar actualizar un producto");
            }
        }
    }//GEN-LAST:event_jLabelBtnModificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBtnBuscar;
    private javax.swing.JLabel jLabelBtnModificar;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodigoPdt;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelPrezio;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JPanel jPanelBtnBuscar;
    private javax.swing.JPanel jPanelBtnModificar;
    private javax.swing.JPanel jPanelFondoTabla;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTableUpdate;
    private javax.swing.JTextField jTextFieldCodigoPdt;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldPrezio;
    // End of variables declaration//GEN-END:variables
}
