/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nrodas.archivosp1.interfazgrafica;

import com.nrodas.archivosp1.apoyo.LlenadorTabla;
import com.nrodas.archivosp1.entidades.Producto;
import com.nrodas.archivosp1.entidades.Reporte;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * Clase que maneja el panel 1 de bodega
 * @author lroda
 */
public class Bod_Pnl1 extends javax.swing.JPanel {

    /**
     * Atributos
     */
    private final Reporte reporte;
    
    /**
     * Constructor
     */
    public Bod_Pnl1() {
        initComponents();
        reporte = new Reporte();
        LlenadorTabla.cambiarEncabezado(this.jTablePdtBodega, new String[]{"Codigo Producto", "Descripcion", "Cantidad", "Precio Unitario"});
        reporte.retornarProductosInventario(1);
        LlenadorTabla.llenarTablaInventario(this.jTablePdtBodega, reporte.getLb());
        this.setSize(980, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelT1 = new javax.swing.JLabel();
        jLabelCodigoPdt = new javax.swing.JLabel();
        jTextFieldCodigoPdt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelDescripcion = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelCantidad = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jPanelBtnAgregar = new javax.swing.JPanel();
        jLabelBtnAgregar = new javax.swing.JLabel();
        jPanelFondoTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePdtBodega = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelT1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelT1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelT1.setText("Registra nuevos productos");
        add(jLabelT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 510, -1));

        jLabelCodigoPdt.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelCodigoPdt.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodigoPdt.setText("Ingresa el codigo del nuevo producto: ");
        add(jLabelCodigoPdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 450, -1));

        jTextFieldCodigoPdt.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoPdt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldCodigoPdt.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCodigoPdt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigoPdt.setBorder(null);
        jTextFieldCodigoPdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoPdtKeyTyped(evt);
            }
        });
        add(jTextFieldCodigoPdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 170, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 170, 10));

        jLabelDescripcion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescripcion.setText("Descipcion del nuevo producto: ");
        add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 380, -1));

        jTextFieldDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescripcion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDescripcion.setBorder(null);
        jTextFieldDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescripcionKeyTyped(evt);
            }
        });
        add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 240, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 240, 10));

        jLabelPrecio.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecio.setText("Precio: ");
        add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 100, -1));

        jTextFieldPrecio.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPrecio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecio.setBorder(null);
        jTextFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyTyped(evt);
            }
        });
        add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 150, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 150, 10));

        jLabelCantidad.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantidad.setText("Cantidad: ");
        add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 130, -1));

        jSpinnerCantidad.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 80, 30));

        jPanelBtnAgregar.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBtnAgregar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelBtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnAgregar.setText("Agregar");
        jLabelBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnAgregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnAgregarLayout = new javax.swing.GroupLayout(jPanelBtnAgregar);
        jPanelBtnAgregar.setLayout(jPanelBtnAgregarLayout);
        jPanelBtnAgregarLayout.setHorizontalGroup(
            jPanelBtnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanelBtnAgregarLayout.setVerticalGroup(
            jPanelBtnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanelBtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 150, 40));

        jPanelFondoTabla.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTablePdtBodega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePdtBodega);

        javax.swing.GroupLayout jPanelFondoTablaLayout = new javax.swing.GroupLayout(jPanelFondoTabla);
        jPanelFondoTabla.setLayout(jPanelFondoTablaLayout);
        jPanelFondoTablaLayout.setHorizontalGroup(
            jPanelFondoTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanelFondoTablaLayout.setVerticalGroup(
            jPanelFondoTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        add(jPanelFondoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 880, 300));
    }// </editor-fold>//GEN-END:initComponents

    
    /*
        Eventos relacionados con el boton agregar
    */
    private void jLabelBtnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnAgregarMouseEntered
        this.jPanelBtnAgregar.setBackground(new Color(152, 155, 158));
    }//GEN-LAST:event_jLabelBtnAgregarMouseEntered

    private void jLabelBtnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnAgregarMouseExited
        this.jPanelBtnAgregar.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBtnAgregarMouseExited

    /*
        Eventos relacionados con los Jtextfields
    */
    private void jTextFieldCodigoPdtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPdtKeyTyped
        if (this.jTextFieldCodigoPdt.getText().length() > 11) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldCodigoPdtKeyTyped

    private void jTextFieldPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == '.')) {
            evt.consume();
        }
        if (c == '.' && this.jTextFieldPrecio.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrecioKeyTyped

    private void jTextFieldDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionKeyTyped
        if (this.jTextFieldDescripcion.getText().length() > 99) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldDescripcionKeyTyped

    /*
        Evento relacionado con el evento de click del boton agregar
    */
    private void jLabelBtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnAgregarMouseClicked
        String codigoPdt = this.jTextFieldCodigoPdt.getText().trim();
        String descripcion = this.jTextFieldDescripcion.getText().trim();
        String precio = this.jTextFieldPrecio.getText().trim();
        if (!codigoPdt.isBlank() && !descripcion.isBlank() && !precio.isBlank()) {
            Producto producto = new Producto();
            if (!producto.buscarProducto(codigoPdt, 1)) {
                double prezio = Double.valueOf(precio);
                int cantidad = Integer.valueOf(String.valueOf(this.jSpinnerCantidad.getValue()));
                producto = new Producto(codigoPdt, 1, descripcion, cantidad, prezio);
                producto.insertarProducto();
                this.setearValores();
                JOptionPane.showMessageDialog(null, "Producto Agregado con Exito");
            } else {
                JOptionPane.showMessageDialog(null, "El producto ya existe");
            }            
        }
    }//GEN-LAST:event_jLabelBtnAgregarMouseClicked

    /**
     *
     */
    public void setearValores(){
        this.jTextFieldCodigoPdt.setText("");
        this.jTextFieldDescripcion.setText("");
        this.jTextFieldPrecio.setText("");
        this.jSpinnerCantidad.setValue(1);
        LlenadorTabla.cambiarEncabezado(this.jTablePdtBodega, new String[]{"Codigo Producto", "Descripcion", "Cantidad", "Precio Unitario"});
        reporte.retornarProductosInventario(1);
        LlenadorTabla.llenarTablaInventario(this.jTablePdtBodega, reporte.getLb());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBtnAgregar;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodigoPdt;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JPanel jPanelBtnAgregar;
    private javax.swing.JPanel jPanelFondoTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTablePdtBodega;
    private javax.swing.JTextField jTextFieldCodigoPdt;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
