/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nrodas.archivosp1.interfazgrafica;

import com.nrodas.archivosp1.conexion.Conexion;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 * Clase que maneja la UI de Bodega
 * @author lroda
 */
public class Bodega extends javax.swing.JFrame {

    /**
     * Atributos
     */
    private int moveX;
    private int moveY;

    /**
     * Constructor
     */
    public Bodega() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Icono-App.png")).getImage());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelBarraLateral = new javax.swing.JPanel();
        jLabelT1 = new javax.swing.JLabel();
        jLabelT2 = new javax.swing.JLabel();
        jPanelBtnCS = new javax.swing.JPanel();
        jLabelBtnCS = new javax.swing.JLabel();
        jLabelICS = new javax.swing.JLabel();
        jPanelBtnHome = new javax.swing.JPanel();
        jLabelBtnHome = new javax.swing.JLabel();
        jLabelIH = new javax.swing.JLabel();
        jPanelBtnIngresar = new javax.swing.JPanel();
        jLabelBtnIngresar = new javax.swing.JLabel();
        jLabelIIP = new javax.swing.JLabel();
        jPanelBtnModificar = new javax.swing.JPanel();
        jLabelBtnModificar = new javax.swing.JLabel();
        jLabelIMP = new javax.swing.JLabel();
        jPanelBarraSup = new javax.swing.JPanel();
        jPanelBtnCerrar = new javax.swing.JPanel();
        jLabelBtnCerrar = new javax.swing.JLabel();
        jPanelBtnMin = new javax.swing.JPanel();
        jLabelBtnMin = new javax.swing.JLabel();
        jPanelCambiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBarraLateral.setBackground(new java.awt.Color(255, 227, 0));
        jPanelBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelT1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelT1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelT1.setText("ELECTRONIC");
        jPanelBarraLateral.add(jLabelT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, -1));

        jLabelT2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelT2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelT2.setText("HOMES");
        jPanelBarraLateral.add(jLabelT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, -1));

        jPanelBtnCS.setBackground(new java.awt.Color(255, 227, 0));
        jPanelBtnCS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBtnCS.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        jLabelBtnCS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnCS.setText("     Cerrar Seción");
        jLabelBtnCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnCSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnCSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnCSMouseExited(evt);
            }
        });
        jPanelBtnCS.add(jLabelBtnCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabelICS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelICS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close-Icon.png"))); // NOI18N
        jPanelBtnCS.add(jLabelICS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 60));

        jPanelBarraLateral.add(jPanelBtnCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 300, 60));

        jPanelBtnHome.setBackground(new java.awt.Color(255, 227, 0));
        jPanelBtnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBtnHome.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        jLabelBtnHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnHome.setText("     Inicio");
        jLabelBtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnHomeMouseExited(evt);
            }
        });
        jPanelBtnHome.add(jLabelBtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabelIH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home-Icon.png"))); // NOI18N
        jPanelBtnHome.add(jLabelIH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 60));

        jPanelBarraLateral.add(jPanelBtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 300, 60));

        jPanelBtnIngresar.setBackground(new java.awt.Color(255, 227, 0));
        jPanelBtnIngresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBtnIngresar.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        jLabelBtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnIngresar.setText("     Ingr. Productos");
        jLabelBtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnIngresarMouseExited(evt);
            }
        });
        jPanelBtnIngresar.add(jLabelBtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabelIIP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IngPdt.png"))); // NOI18N
        jPanelBtnIngresar.add(jLabelIIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 60));

        jPanelBarraLateral.add(jPanelBtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 60));

        jPanelBtnModificar.setBackground(new java.awt.Color(255, 227, 0));
        jPanelBtnModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBtnModificar.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        jLabelBtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnModificar.setText("     Mod. Productos");
        jLabelBtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnModificarMouseExited(evt);
            }
        });
        jPanelBtnModificar.add(jLabelBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabelIMP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModPdt.png"))); // NOI18N
        jPanelBtnModificar.add(jLabelIMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 60));

        jPanelBarraLateral.add(jPanelBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 300, 60));

        jPanel1.add(jPanelBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        jPanelBarraSup.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBarraSup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelBarraSupMouseDragged(evt);
            }
        });
        jPanelBarraSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBarraSupMousePressed(evt);
            }
        });
        jPanelBarraSup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBtnCerrar.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBtnCerrar.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabelBtnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBtnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnCerrar.setText("x");
        jLabelBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnCerrarLayout = new javax.swing.GroupLayout(jPanelBtnCerrar);
        jPanelBtnCerrar.setLayout(jPanelBtnCerrarLayout);
        jPanelBtnCerrarLayout.setHorizontalGroup(
            jPanelBtnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBtnCerrarLayout.setVerticalGroup(
            jPanelBtnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBarraSup.add(jPanelBtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, -1, -1));

        jPanelBtnMin.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBtnMin.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabelBtnMin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBtnMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnMin.setText("_");
        jLabelBtnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnMinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnMinLayout = new javax.swing.GroupLayout(jPanelBtnMin);
        jPanelBtnMin.setLayout(jPanelBtnMinLayout);
        jPanelBtnMinLayout.setHorizontalGroup(
            jPanelBtnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnMinLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBtnMinLayout.setVerticalGroup(
            jPanelBtnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnMinLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBarraSup.add(jPanelBtnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, -1));

        jPanel1.add(jPanelBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 30));

        jPanelCambiante.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCambiante.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanelCambiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 980, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
        Metodos relacionados con la barra superior
     */
    private void jPanelBarraSupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraSupMousePressed
        this.moveX = evt.getX();
        this.moveY = evt.getY();
    }//GEN-LAST:event_jPanelBarraSupMousePressed

    private void jPanelBarraSupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraSupMouseDragged
        int pFx = evt.getXOnScreen();
        int pFy = evt.getYOnScreen();
        this.setLocation(pFx - this.moveX, pFy - this.moveY);
    }//GEN-LAST:event_jPanelBarraSupMouseDragged

    /*
        Metodos Relacionados con los botones de cerrar y minimizar
     */
    private void jLabelBtnMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnMinMouseEntered
        this.jPanelBtnMin.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_jLabelBtnMinMouseEntered

    private void jLabelBtnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnMinMouseExited
        this.jPanelBtnMin.setBackground(Color.white);
    }//GEN-LAST:event_jLabelBtnMinMouseExited

    private void jLabelBtnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnMinMouseClicked
        this.setExtendedState(Bodega.ICONIFIED);
    }//GEN-LAST:event_jLabelBtnMinMouseClicked

    private void jLabelBtnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCerrarMouseEntered
        this.jPanelBtnCerrar.setBackground(Color.red);
        this.jLabelBtnCerrar.setForeground(Color.white);
    }//GEN-LAST:event_jLabelBtnCerrarMouseEntered

    private void jLabelBtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCerrarMouseExited
        this.jPanelBtnCerrar.setBackground(Color.white);
        this.jLabelBtnCerrar.setForeground(Color.black);
    }//GEN-LAST:event_jLabelBtnCerrarMouseExited

    private void jLabelBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCerrarMouseClicked
        Conexion.cerrarConexionDB();
        System.exit(0);
    }//GEN-LAST:event_jLabelBtnCerrarMouseClicked

    /*
        Metodos relacionados con los botones y sus click
     */
    private void jLabelBtnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnHomeMouseEntered
        this.jPanelBtnHome.setBackground(new Color(255, 238, 52));
    }//GEN-LAST:event_jLabelBtnHomeMouseEntered

    private void jLabelBtnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnHomeMouseExited
        if (this.jLabelBtnHome.isEnabled()) {
            this.jPanelBtnHome.setBackground(new Color(255, 227, 0));
        }
    }//GEN-LAST:event_jLabelBtnHomeMouseExited

    private void jLabelBtnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnIngresarMouseEntered
        this.jPanelBtnIngresar.setBackground(new Color(255, 238, 52));
    }//GEN-LAST:event_jLabelBtnIngresarMouseEntered

    private void jLabelBtnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnIngresarMouseExited
        if (this.jLabelBtnIngresar.isEnabled()) {
            this.jPanelBtnIngresar.setBackground(new Color(255, 227, 0));
        }
    }//GEN-LAST:event_jLabelBtnIngresarMouseExited

    private void jLabelBtnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnModificarMouseEntered
        this.jPanelBtnModificar.setBackground(new Color(255, 238, 52));
    }//GEN-LAST:event_jLabelBtnModificarMouseEntered

    private void jLabelBtnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnModificarMouseExited
        if (this.jLabelBtnModificar.isEnabled()) {
            this.jPanelBtnModificar.setBackground(new Color(255, 227, 0));
        }
    }//GEN-LAST:event_jLabelBtnModificarMouseExited

    private void jLabelBtnCSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCSMouseEntered
        this.jPanelBtnCS.setBackground(new Color(255, 238, 52));
    }//GEN-LAST:event_jLabelBtnCSMouseEntered

    private void jLabelBtnCSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCSMouseExited
        this.jPanelBtnCS.setBackground(new Color(255, 227, 0));
    }//GEN-LAST:event_jLabelBtnCSMouseExited

    /*
        Eventos relacionados con los click de las opciones del menu lateral
     */
    private void jLabelBtnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnHomeMouseClicked
        if (!this.jLabelBtnIngresar.isEnabled()) {
            this.jLabelBtnIngresar.setEnabled(true);
            this.jLabelIIP.setEnabled(true);
            this.jPanelBtnIngresar.setBackground(new Color(255, 227, 0));
        } else if (!this.jLabelBtnModificar.isEnabled()) {
            this.jLabelBtnModificar.setEnabled(true);
            this.jLabelIMP.setEnabled(true);
            this.jPanelBtnModificar.setBackground(new Color(255, 227, 0));
        }
        this.jLabelBtnHome.setEnabled(false);
        this.jLabelIH.setEnabled(false);
        Inicio_Pnl home = new Inicio_Pnl();
        this.jPanelCambiante.removeAll();
        this.jPanelCambiante.add(home);
        this.jPanelCambiante.repaint();
        this.jPanelCambiante.revalidate();
    }//GEN-LAST:event_jLabelBtnHomeMouseClicked

    private void jLabelBtnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnIngresarMouseClicked
        if (!this.jLabelBtnHome.isEnabled()) {
            this.jLabelBtnHome.setEnabled(true);
            this.jLabelIH.setEnabled(true);
            this.jPanelBtnHome.setBackground(new Color(255, 227, 0));
        } else if (!this.jLabelBtnModificar.isEnabled()) {
            this.jLabelBtnModificar.setEnabled(true);
            this.jLabelIMP.setEnabled(true);
            this.jPanelBtnModificar.setBackground(new Color(255, 227, 0));
        }
        this.jLabelBtnIngresar.setEnabled(false);
        this.jLabelIIP.setEnabled(false);
        Bod_Pnl1 panel = new Bod_Pnl1();
        this.jPanelCambiante.removeAll();
        this.jPanelCambiante.add(panel);
        this.jPanelCambiante.repaint();
        this.jPanelCambiante.revalidate();
    }//GEN-LAST:event_jLabelBtnIngresarMouseClicked

    private void jLabelBtnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnModificarMouseClicked
        if (!this.jLabelBtnHome.isEnabled()) {
            this.jLabelBtnHome.setEnabled(true);
            this.jLabelIH.setEnabled(true);
            this.jPanelBtnHome.setBackground(new Color(255, 227, 0));
        } else if (!this.jLabelBtnIngresar.isEnabled()) {
            this.jLabelBtnIngresar.setEnabled(true);
            this.jLabelIIP.setEnabled(true);
            this.jPanelBtnIngresar.setBackground(new Color(255, 227, 0));
        }
        this.jLabelBtnModificar.setEnabled(false);
        this.jLabelIMP.setEnabled(false);
        Bod_Pnl2 panel = new Bod_Pnl2();
        this.jPanelCambiante.removeAll();
        this.jPanelCambiante.add(panel);
        this.jPanelCambiante.repaint();
        this.jPanelCambiante.revalidate();
    }//GEN-LAST:event_jLabelBtnModificarMouseClicked

    private void jLabelBtnCSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCSMouseClicked
        Login login = new Login();
        EmpLogueado.reiniciarValores();
        this.dispose();
    }//GEN-LAST:event_jLabelBtnCSMouseClicked

    /**
     * Metodo que repinta el panel
     */
    public void repintarModPdt() {
        Bod_Pnl2 panel = new Bod_Pnl2();
        this.jPanelCambiante.removeAll();
        this.jPanelCambiante.add(panel);
        this.jPanelCambiante.repaint();
        this.jPanelCambiante.revalidate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBtnCS;
    private javax.swing.JLabel jLabelBtnCerrar;
    private javax.swing.JLabel jLabelBtnHome;
    private javax.swing.JLabel jLabelBtnIngresar;
    private javax.swing.JLabel jLabelBtnMin;
    private javax.swing.JLabel jLabelBtnModificar;
    private javax.swing.JLabel jLabelICS;
    private javax.swing.JLabel jLabelIH;
    private javax.swing.JLabel jLabelIIP;
    private javax.swing.JLabel jLabelIMP;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JLabel jLabelT2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBarraLateral;
    private javax.swing.JPanel jPanelBarraSup;
    private javax.swing.JPanel jPanelBtnCS;
    private javax.swing.JPanel jPanelBtnCerrar;
    private javax.swing.JPanel jPanelBtnHome;
    private javax.swing.JPanel jPanelBtnIngresar;
    private javax.swing.JPanel jPanelBtnMin;
    private javax.swing.JPanel jPanelBtnModificar;
    private javax.swing.JPanel jPanelCambiante;
    // End of variables declaration//GEN-END:variables
}
