/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nrodas.archivosp1.interfazgrafica;

import com.nrodas.archivosp1.apoyo.Conversor;
import com.nrodas.archivosp1.apoyo.LlenadorTabla;
import com.nrodas.archivosp1.entidades.Producto;
import com.nrodas.archivosp1.entidades.Reporte;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;

/**
 * Clase encargada del panel 1 de inventario
 * @author lroda
 */
public class Inv_Pnl1 extends javax.swing.JPanel {

    /**
     * Atributos
     */
    private Reporte reporte;
    private Producto prt;
    
    /**
     * Constructor
     */
    public Inv_Pnl1() {
        initComponents();
        this.reporte = new Reporte();
        String suc = Conversor.determinarNombreSucursal(EmpLogueado.empleadoLogueado.getSucursal());
        this.jLabelSucursal.setText(suc);
        this.jComboBoxInstalacion.removeItem(suc);
        this.setSize(980, 650);
        this.jPanelFondoTabla.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSucursal = new javax.swing.JLabel();
        jLabelSP = new javax.swing.JLabel();
        jComboBoxInstalacion = new javax.swing.JComboBox<>();
        jLabelCodigoPdt = new javax.swing.JLabel();
        jTextFieldCodigoPdt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCantidad = new javax.swing.JLabel();
        jPanelBtnBuscar = new javax.swing.JPanel();
        jLabelBtnBuscar = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jPanelFondoTabla = new javax.swing.JPanel();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanelBtnAdquirir = new javax.swing.JPanel();
        jLabelBtnAdquirir = new javax.swing.JLabel();
        jPanelBtnMostrarA = new javax.swing.JPanel();
        jLabelMPSA = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSucursal.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelSucursal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSucursal.setText("jLabel1");
        add(jLabelSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 260, -1));

        jLabelSP.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelSP.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSP.setText("Instalacion Proveedora: ");
        add(jLabelSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 260, -1));

        jComboBoxInstalacion.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxInstalacion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jComboBoxInstalacion.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxInstalacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bodega", "Sucursal Central", "Sucursal Norte", "Sucursal Sur" }));
        jComboBoxInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInstalacionActionPerformed(evt);
            }
        });
        add(jComboBoxInstalacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 170, 30));

        jLabelCodigoPdt.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelCodigoPdt.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodigoPdt.setText("Codigo del Producto: ");
        add(jLabelCodigoPdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, -1));

        jTextFieldCodigoPdt.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoPdt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldCodigoPdt.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCodigoPdt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigoPdt.setBorder(null);
        jTextFieldCodigoPdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoPdtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoPdtKeyTyped(evt);
            }
        });
        add(jTextFieldCodigoPdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 190, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, 10));

        jLabelCantidad.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantidad.setText("Cantidad: ");
        add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 120, -1));

        jPanelBtnBuscar.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBtnBuscar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelBtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuscarPdt.png"))); // NOI18N
        jLabelBtnBuscar.setText("Buscar");
        jLabelBtnBuscar.setEnabled(false);
        jLabelBtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnBuscarLayout = new javax.swing.GroupLayout(jPanelBtnBuscar);
        jPanelBtnBuscar.setLayout(jPanelBtnBuscarLayout);
        jPanelBtnBuscarLayout.setHorizontalGroup(
            jPanelBtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanelBtnBuscarLayout.setVerticalGroup(
            jPanelBtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(jPanelBtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 150, 30));

        jSpinnerCantidad.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));
        jSpinnerCantidad.setEnabled(false);
        add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 70, 30));

        jPanelFondoTabla.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondoTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneProductos.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneProductos.setBorder(null);
        jScrollPaneProductos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneProductos.setToolTipText("");

        jTableProductos.setBackground(new java.awt.Color(255, 255, 255));
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneProductos.setViewportView(jTableProductos);

        jPanelFondoTabla.add(jScrollPaneProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 400));

        jPanelBtnAdquirir.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBtnAdquirir.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelBtnAdquirir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnAdquirir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnAdquirir.setText("Adquirir");
        jLabelBtnAdquirir.setEnabled(false);
        jLabelBtnAdquirir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnAdquirirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnAdquirirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnAdquirirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnAdquirirLayout = new javax.swing.GroupLayout(jPanelBtnAdquirir);
        jPanelBtnAdquirir.setLayout(jPanelBtnAdquirirLayout);
        jPanelBtnAdquirirLayout.setHorizontalGroup(
            jPanelBtnAdquirirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnAdquirir, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanelBtnAdquirirLayout.setVerticalGroup(
            jPanelBtnAdquirirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBtnAdquirir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelFondoTabla.add(jPanelBtnAdquirir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 160, 40));

        jPanelBtnMostrarA.setBackground(new java.awt.Color(94, 96, 98));

        jLabelMPSA.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelMPSA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMPSA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMPSA.setText("Mostrar Producto de esta Sucursal");
        jLabelMPSA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMPSAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMPSAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMPSAMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnMostrarALayout = new javax.swing.GroupLayout(jPanelBtnMostrarA);
        jPanelBtnMostrarA.setLayout(jPanelBtnMostrarALayout);
        jPanelBtnMostrarALayout.setHorizontalGroup(
            jPanelBtnMostrarALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMPSA, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jPanelBtnMostrarALayout.setVerticalGroup(
            jPanelBtnMostrarALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMPSA, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelFondoTabla.add(jPanelBtnMostrarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 290, 40));

        add(jPanelFondoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 880, 480));
    }// </editor-fold>//GEN-END:initComponents

    /*
        Metodos relacionado scon los desvanecimientos de los botones
    */
    
    private void jLabelBtnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnBuscarMouseEntered
        if (this.jLabelBtnBuscar.isEnabled()) {
            this.jPanelBtnBuscar.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelBtnBuscarMouseEntered

    private void jLabelBtnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnBuscarMouseExited
        this.jPanelBtnBuscar.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBtnBuscarMouseExited

    private void jLabelBtnAdquirirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnAdquirirMouseEntered
        if (this.jLabelBtnAdquirir.isEnabled()) {
            this.jPanelBtnAdquirir.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelBtnAdquirirMouseEntered

    private void jLabelBtnAdquirirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnAdquirirMouseExited
        this.jPanelBtnAdquirir.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBtnAdquirirMouseExited

    /*Eventos Relacionados con el textfield*/
    
    private void jTextFieldCodigoPdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPdtKeyReleased
        if (this.jTextFieldCodigoPdt.getText().isBlank()) {
            this.jLabelBtnBuscar.setEnabled(false);
        } else {
            this.jLabelBtnBuscar.setEnabled(true);
        }
        int cod = evt.getKeyCode();
        if (cod == KeyEvent.VK_BACK_SPACE || cod == KeyEvent.VK_DELETE) {
            if (this.jLabelBtnAdquirir.isEnabled()) {
                this.jLabelBtnAdquirir.setEnabled(false);
                this.jSpinnerCantidad.setValue(1);
                this.jSpinnerCantidad.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jTextFieldCodigoPdtKeyReleased

    private void jTextFieldCodigoPdtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPdtKeyTyped
        String texto = this.jTextFieldCodigoPdt.getText().trim();
        if (texto.length() > 11) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldCodigoPdtKeyTyped

    /*
        Metodo Relacionado con el click del buton buscar
    */
    
    private void jLabelBtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnBuscarMouseClicked
        int inventario = Conversor.determinarSucursal(String.valueOf(this.jComboBoxInstalacion.getSelectedItem()));
        this.prt = new Producto();
        if (this.prt.buscarProducto(this.jTextFieldCodigoPdt.getText(), inventario)) {
            this.jLabelBtnAdquirir.setEnabled(true);
            SpinnerNumberModel modelo = (SpinnerNumberModel)this.jSpinnerCantidad.getModel();
            modelo.setMaximum(this.prt.getCantidad());
            this.jSpinnerCantidad.setEnabled(true);
        }
    }//GEN-LAST:event_jLabelBtnBuscarMouseClicked

    /*Metodo relacionado con el jcombobox*/
    
    private void jComboBoxInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInstalacionActionPerformed
        String item = String.valueOf(this.jComboBoxInstalacion.getSelectedItem()).trim();
        LlenadorTabla.cambiarEncabezado(jTableProductos, new String[]{"Codigo Producto", "Descripcion", "Cantidad", "Precio Unitario"});
        switch (item) {
            case "Bodega":
                this.reporte.retornarProductosInventario(1);
                break;
            case "Sucursal Central":
                this.reporte.retornarProductosInventario(2);
                break;
            case "Sucursal Norte":
                this.reporte.retornarProductosInventario(3);
                break;
            case "Sucursal Sur":
                this.reporte.retornarProductosInventario(4);
                break;
        }
        LlenadorTabla.llenarTablaInventario(jTableProductos, this.reporte.getLb());
        if (!this.jPanelFondoTabla.isVisible()) {
            this.jPanelFondoTabla.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxInstalacionActionPerformed

    /*Evento relacionado con el click de adquirir*/
    
    private void jLabelBtnAdquirirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnAdquirirMouseClicked
        Producto product = new Producto(); //Se crea una nueva instancia de producto
        int inventario = Conversor.determinarSucursal(this.jLabelSucursal.getText().trim()); //Se determina su inventario
        String producto = this.jTextFieldCodigoPdt.getText(); //Se obtiene el codigo del prodcuto a travez del jtextfield
        int cantidad = Integer.valueOf(String.valueOf(this.jSpinnerCantidad.getValue())); //Se obtiene su nueva cantidad
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this); //Obtiene el frame en el que se encuentra el panel
        if (this.jLabelBtnAdquirir.isEnabled()) { //Valida que el boton este disponible
            if (product.buscarProducto(producto, inventario)) { //Valida que el producto exista
                if (!this.prt.getDescripcionProducto().equals(product.getDescripcionProducto())) { //Valida si tienen el mismo nombre
                    product.acutalizatDesc(this.prt.getDescripcionProducto()); //Lo actualizo si es le caso de que no
                }
                if (this.prt.getPrecioUnitario() != product.getPrecioUnitario()) { //Valida si tienen el mismo precio
                    product.actualizarPrezio(this.prt.getPrecioUnitario()); //Lo actualiza si no es el caso
                }
                //Actualiza los stocks
                product.actualizarStock(producto, inventario, product.getCantidad() + cantidad);
                this.prt.actualizarStock(this.prt.getCodigoProducto(), this.prt.getInventario(), this.prt.getCantidad() - cantidad);
                ShowMsg msg = new ShowMsg(frame, true, "Stocks Actualizados");
            } else { //Inserta el producto por si no existe ahi
                Producto pdt = new Producto(producto, inventario, this.prt.getDescripcionProducto(), cantidad, this.prt.getPrecioUnitario());
                pdt.insertarProducto();
                this.prt.actualizarStock(this.prt.getCodigoProducto(), this.prt.getInventario(), this.prt.getCantidad() - cantidad);
                ShowMsg msg = new ShowMsg(frame, true, "El producto ha sido agregado y se han removido las existencias adquiridas de la instalacion proveedora");
            }
            Inventario invent = (Inventario)SwingUtilities.getWindowAncestor(this);
            invent.repintarPest();
        }
    }//GEN-LAST:event_jLabelBtnAdquirirMouseClicked

    /*
        Metodo Relacionados con el click de mostrar los productos de la sucursla actual
    */
    
    private void jLabelMPSAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMPSAMouseEntered
        this.jPanelBtnMostrarA.setBackground(new Color(152, 155, 158));
    }//GEN-LAST:event_jLabelMPSAMouseEntered

    private void jLabelMPSAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMPSAMouseExited
        this.jPanelBtnMostrarA.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelMPSAMouseExited

    private void jLabelMPSAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMPSAMouseClicked
        int inventario = Conversor.determinarSucursal(this.jLabelSucursal.getText().trim());
        LlenadorTabla.cambiarEncabezado(jTableProductos, new String[]{"Codigo Producto", "Descripcion", "Cantidad", "Precio Unitario"});
        reporte.retornarProductosInventario(inventario);
        LlenadorTabla.llenarTablaInventario(jTableProductos, this.reporte.getLb());
    }//GEN-LAST:event_jLabelMPSAMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxInstalacion;
    private javax.swing.JLabel jLabelBtnAdquirir;
    private javax.swing.JLabel jLabelBtnBuscar;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodigoPdt;
    private javax.swing.JLabel jLabelMPSA;
    private javax.swing.JLabel jLabelSP;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JPanel jPanelBtnAdquirir;
    private javax.swing.JPanel jPanelBtnBuscar;
    private javax.swing.JPanel jPanelBtnMostrarA;
    private javax.swing.JPanel jPanelFondoTabla;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldCodigoPdt;
    // End of variables declaration//GEN-END:variables
}
