/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nrodas.archivosp1.interfazgrafica;

import com.nrodas.archivosp1.conexion.Conexion;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 * Clase encargada de generar la UI de Ventas
 * @author lroda
 */
public class VentaR extends javax.swing.JFrame {

    /**
     * Atributos
     */
    int moveX;
    int moveY;
    
    /**
     * Constructor
     */
    public VentaR() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Icono-App.png")).getImage());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelT2 = new javax.swing.JLabel();
        jPanelMenuLateral = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jLabelBtnInicio = new javax.swing.JLabel();
        jPanelGenerarVentas = new javax.swing.JPanel();
        jLabelSales = new javax.swing.JLabel();
        jLabelBtnGenerarVenta = new javax.swing.JLabel();
        jPanelActualizarClientes = new javax.swing.JPanel();
        jLabelClient = new javax.swing.JLabel();
        jLabelBtnActualizarClientes = new javax.swing.JLabel();
        jPanelCerrarSecion = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelBtnCerrarSecion = new javax.swing.JLabel();
        jLabelT1 = new javax.swing.JLabel();
        jPanelBarraSuperior = new javax.swing.JPanel();
        jPanelBtnMinmizar = new javax.swing.JPanel();
        jLabelBtnMinimizar = new javax.swing.JLabel();
        jPanelBtnCerrar = new javax.swing.JPanel();
        jLabelBtnCerrar = new javax.swing.JLabel();
        jPanelCambiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelT2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelT2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelT2.setText("HOMES");
        jPanelFondo.add(jLabelT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 300, -1));

        jPanelMenuLateral.setBackground(new java.awt.Color(0, 255, 25));
        jPanelMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHome.setBackground(new java.awt.Color(0, 255, 25));
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home-Icon.png"))); // NOI18N
        jPanelHome.add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 50, 60));

        jLabelBtnInicio.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        jLabelBtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnInicio.setText("      Inicio");
        jLabelBtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnInicioMouseExited(evt);
            }
        });
        jPanelHome.add(jLabelBtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jPanelMenuLateral.add(jPanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, 60));

        jPanelGenerarVentas.setBackground(new java.awt.Color(0, 255, 25));
        jPanelGenerarVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sales-Icon.png"))); // NOI18N
        jPanelGenerarVentas.add(jLabelSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 50, 60));

        jLabelBtnGenerarVenta.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        jLabelBtnGenerarVenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnGenerarVenta.setText("      Generar Venta");
        jLabelBtnGenerarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnGenerarVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnGenerarVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnGenerarVentaMouseExited(evt);
            }
        });
        jPanelGenerarVentas.add(jLabelBtnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jPanelMenuLateral.add(jPanelGenerarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 300, 60));

        jPanelActualizarClientes.setBackground(new java.awt.Color(0, 255, 25));
        jPanelActualizarClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client-Icon.png"))); // NOI18N
        jPanelActualizarClientes.add(jLabelClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));

        jLabelBtnActualizarClientes.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        jLabelBtnActualizarClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnActualizarClientes.setText("      Modificar Cliente");
        jLabelBtnActualizarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnActualizarClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnActualizarClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnActualizarClientesMouseExited(evt);
            }
        });
        jPanelActualizarClientes.add(jLabelBtnActualizarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jPanelMenuLateral.add(jPanelActualizarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 60));

        jPanelCerrarSecion.setBackground(new java.awt.Color(0, 255, 25));
        jPanelCerrarSecion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close-Icon.png"))); // NOI18N
        jPanelCerrarSecion.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -2, 50, 60));

        jLabelBtnCerrarSecion.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        jLabelBtnCerrarSecion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnCerrarSecion.setText("      Cerrar Secion");
        jLabelBtnCerrarSecion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnCerrarSecionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnCerrarSecionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnCerrarSecionMouseExited(evt);
            }
        });
        jPanelCerrarSecion.add(jLabelBtnCerrarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jPanelMenuLateral.add(jPanelCerrarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 300, 60));

        jLabelT1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelT1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelT1.setText("ELECTRONIC");
        jPanelMenuLateral.add(jLabelT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, -1));

        jPanelFondo.add(jPanelMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        jPanelBarraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelBarraSuperiorMouseDragged(evt);
            }
        });
        jPanelBarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBarraSuperiorMousePressed(evt);
            }
        });
        jPanelBarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBtnMinmizar.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBtnMinimizar.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabelBtnMinimizar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBtnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnMinimizar.setText("_");
        jLabelBtnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnMinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnMinmizarLayout = new javax.swing.GroupLayout(jPanelBtnMinmizar);
        jPanelBtnMinmizar.setLayout(jPanelBtnMinmizarLayout);
        jPanelBtnMinmizarLayout.setHorizontalGroup(
            jPanelBtnMinmizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnMinmizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBtnMinmizarLayout.setVerticalGroup(
            jPanelBtnMinmizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnMinmizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBarraSuperior.add(jPanelBtnMinmizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 30, -1));

        jPanelBtnCerrar.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBtnCerrar.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabelBtnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBtnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnCerrar.setText("x");
        jLabelBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnCerrarLayout = new javax.swing.GroupLayout(jPanelBtnCerrar);
        jPanelBtnCerrar.setLayout(jPanelBtnCerrarLayout);
        jPanelBtnCerrarLayout.setHorizontalGroup(
            jPanelBtnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBtnCerrarLayout.setVerticalGroup(
            jPanelBtnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBarraSuperior.add(jPanelBtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, -1, -1));

        jPanelFondo.add(jPanelBarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 30));

        jPanelCambiante.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCambiante.setForeground(new java.awt.Color(255, 255, 255));
        jPanelCambiante.setLayout(new java.awt.CardLayout());
        jPanelFondo.add(jPanelCambiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 980, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Metodos sobre los paneles para que simulen un boton a la hora de que el mouse entre y salga de ellos*/
    
    private void jLabelBtnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnMinimizarMouseEntered
        this.jPanelBtnMinmizar.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_jLabelBtnMinimizarMouseEntered

    private void jLabelBtnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnMinimizarMouseExited
        this.jPanelBtnMinmizar.setBackground(Color.white);
    }//GEN-LAST:event_jLabelBtnMinimizarMouseExited

    private void jLabelBtnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCerrarMouseEntered
        this.jPanelBtnCerrar.setBackground(Color.red);
        this.jLabelBtnCerrar.setForeground(Color.white);
    }//GEN-LAST:event_jLabelBtnCerrarMouseEntered

    private void jLabelBtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCerrarMouseExited
        this.jPanelBtnCerrar.setBackground(Color.white);
        this.jLabelBtnCerrar.setForeground(Color.black);
    }//GEN-LAST:event_jLabelBtnCerrarMouseExited

    private void jLabelBtnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnInicioMouseEntered
        this.jPanelHome.setBackground(new Color(85, 255, 92));
    }//GEN-LAST:event_jLabelBtnInicioMouseEntered

    private void jLabelBtnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnInicioMouseExited
        if (this.jPanelHome.isEnabled()) {
            this.jPanelHome.setBackground(new Color(0, 255, 25));
        }
    }//GEN-LAST:event_jLabelBtnInicioMouseExited

    private void jLabelBtnGenerarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnGenerarVentaMouseEntered
        this.jPanelGenerarVentas.setBackground(new Color(85, 255, 92));
    }//GEN-LAST:event_jLabelBtnGenerarVentaMouseEntered

    private void jLabelBtnGenerarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnGenerarVentaMouseExited
        if (this.jPanelGenerarVentas.isEnabled()) {
            this.jPanelGenerarVentas.setBackground(new Color(0, 255, 25));
        }
    }//GEN-LAST:event_jLabelBtnGenerarVentaMouseExited

    private void jLabelBtnActualizarClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnActualizarClientesMouseEntered
        this.jPanelActualizarClientes.setBackground(new Color(85, 255, 92));
    }//GEN-LAST:event_jLabelBtnActualizarClientesMouseEntered

    private void jLabelBtnActualizarClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnActualizarClientesMouseExited
        if (this.jPanelActualizarClientes.isEnabled()) {
            this.jPanelActualizarClientes.setBackground(new Color(0, 255, 25));
        }
    }//GEN-LAST:event_jLabelBtnActualizarClientesMouseExited

    private void jLabelBtnCerrarSecionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCerrarSecionMouseEntered
        this.jPanelCerrarSecion.setBackground(new Color(85, 255, 92));
    }//GEN-LAST:event_jLabelBtnCerrarSecionMouseEntered

    private void jLabelBtnCerrarSecionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCerrarSecionMouseExited
        this.jPanelCerrarSecion.setBackground(new Color(0, 255, 25));
    }//GEN-LAST:event_jLabelBtnCerrarSecionMouseExited

    /*Metodos relacionado con el click de los botones*/
    
    private void jLabelBtnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnMinimizarMouseClicked
        this.setExtendedState(VentaR.ICONIFIED);
    }//GEN-LAST:event_jLabelBtnMinimizarMouseClicked

    private void jLabelBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCerrarMouseClicked
        Conexion.cerrarConexionDB();
        System.exit(0);
    }//GEN-LAST:event_jLabelBtnCerrarMouseClicked

    private void jLabelBtnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnInicioMouseClicked
        if (!this.jPanelGenerarVentas.isEnabled()) {
            this.jPanelGenerarVentas.setBackground(new Color(0, 255, 25));
            this.jPanelGenerarVentas.setEnabled(true);
        } else if (!this.jPanelActualizarClientes.isEnabled()) {
            this.jPanelActualizarClientes.setBackground(new Color(0, 255, 25));
            this.jPanelActualizarClientes.setEnabled(true);
        }
        this.jPanelHome.setEnabled(false);
        Inicio_Pnl pnl = new Inicio_Pnl();
        this.jPanelCambiante.removeAll();
        this.jPanelCambiante.add(pnl);
        this.jPanelCambiante.repaint();
        this.jPanelCambiante.revalidate();
    }//GEN-LAST:event_jLabelBtnInicioMouseClicked

    private void jLabelBtnGenerarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnGenerarVentaMouseClicked
        if (!this.jPanelHome.isEnabled()) {
            this.jPanelHome.setBackground(new Color(0, 255, 25));
            this.jPanelHome.setEnabled(true);
        } else if (!this.jPanelActualizarClientes.isEnabled()) {
            this.jPanelActualizarClientes.setBackground(new Color(0, 255, 25));
            this.jPanelActualizarClientes.setEnabled(true);
        }
        this.jPanelGenerarVentas.setEnabled(false);
        Venta_Pnl1 pnl1 = new Venta_Pnl1();
        this.jPanelCambiante.removeAll();
        this.jPanelCambiante.add(pnl1);
        this.jPanelCambiante.repaint();
        this.jPanelCambiante.revalidate();
    }//GEN-LAST:event_jLabelBtnGenerarVentaMouseClicked

    //Metodo relacionado con el comportamiento de la barra superior
    
    private void jPanelBarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraSuperiorMousePressed
        this.moveX = evt.getX();
        this.moveY = evt.getY();
    }//GEN-LAST:event_jPanelBarraSuperiorMousePressed

    private void jPanelBarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraSuperiorMouseDragged
        int pFinalX = evt.getXOnScreen();
        int pFinalY = evt.getYOnScreen();
        this.setLocation(pFinalX - this.moveX, pFinalY - this.moveY);
    }//GEN-LAST:event_jPanelBarraSuperiorMouseDragged

    private void jLabelBtnActualizarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnActualizarClientesMouseClicked
        if (!this.jPanelHome.isEnabled()) {
            this.jPanelHome.setBackground(new Color(0, 255, 25));
            this.jPanelHome.setEnabled(true);
        } else if (!this.jPanelGenerarVentas.isEnabled()) {
            this.jPanelGenerarVentas.setBackground(new Color(0, 255, 25));
            this.jPanelGenerarVentas.setEnabled(true);
        }
        this.jPanelActualizarClientes.setEnabled(false);
        Venta_Pnl2 pnl1 = new Venta_Pnl2();
        this.jPanelCambiante.removeAll();
        this.jPanelCambiante.add(pnl1);
        this.jPanelCambiante.repaint();
        this.jPanelCambiante.revalidate();
    }//GEN-LAST:event_jLabelBtnActualizarClientesMouseClicked

    private void jLabelBtnCerrarSecionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCerrarSecionMouseClicked
        // TODO add your handling code here:
        EmpLogueado.reiniciarValores();
        Login login = new Login();
        this.dispose();
    }//GEN-LAST:event_jLabelBtnCerrarSecionMouseClicked

    /**
     * Metodo que repinta el panel de ventas
     */
    public void repintarPanelVenta() {
        Venta_Pnl1 pnl1 = new Venta_Pnl1();
        this.jPanelCambiante.removeAll();
        this.jPanelCambiante.add(pnl1);
        this.jPanelCambiante.repaint();
        this.jPanelCambiante.revalidate();
    }
    
    /**
     * Metodo que repinta el panel de modficiar clientes
     */
    public void repintarPanelUpdate() {
        Venta_Pnl2 pnl1 = new Venta_Pnl2();
        this.jPanelCambiante.removeAll();
        this.jPanelCambiante.add(pnl1);
        this.jPanelCambiante.repaint();
        this.jPanelCambiante.revalidate();
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBtnActualizarClientes;
    private javax.swing.JLabel jLabelBtnCerrar;
    private javax.swing.JLabel jLabelBtnCerrarSecion;
    private javax.swing.JLabel jLabelBtnGenerarVenta;
    private javax.swing.JLabel jLabelBtnInicio;
    private javax.swing.JLabel jLabelBtnMinimizar;
    private javax.swing.JLabel jLabelClient;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelSales;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JLabel jLabelT2;
    private javax.swing.JPanel jPanelActualizarClientes;
    private javax.swing.JPanel jPanelBarraSuperior;
    private javax.swing.JPanel jPanelBtnCerrar;
    private javax.swing.JPanel jPanelBtnMinmizar;
    private javax.swing.JPanel jPanelCambiante;
    private javax.swing.JPanel jPanelCerrarSecion;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelGenerarVentas;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelMenuLateral;
    // End of variables declaration//GEN-END:variables
}
