/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nrodas.archivosp1.interfazgrafica;

import com.nrodas.archivosp1.apoyo.Conversor;
import com.nrodas.archivosp1.apoyo.LlenadorTabla;
import com.nrodas.archivosp1.entidades.Cliente;
import com.nrodas.archivosp1.entidades.Producto;
import com.nrodas.archivosp1.entidades.Venta;
import com.nrodas.archivosp1.listas.Lista;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;

/**
 * Clase encargada de manejar el panel 1 de ventas
 * @author lroda
 */
public class Venta_Pnl1 extends javax.swing.JPanel {

    /**
     * Atributos
     */
    private Cliente cliente;
    private Venta venta;
    private Producto product;
    private final Date date;
    private ShowMsg msg;
    private JFrame frame;

    /**
     * Constructor
     */
    public Venta_Pnl1() {
        initComponents();
        this.setSize(980, 650);
        date = new Date();
        this.cliente = null;
        this.venta = null;
        this.product = null;
        this.frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        DateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        this.jLabelFecha.setText(this.jLabelFecha.getText() + dateformat.format(date));
        this.jLabelSucursal.setText(Conversor.determinarNombreSucursal(EmpLogueado.empleadoLogueado.getSucursal()));
        this.jLabelIdUsuario.setText(this.jLabelIdUsuario.getText() + EmpLogueado.empleadoLogueado.getIdUsuario());
        this.jPanelAgregarCli.setVisible(false);
        this.jPanelVenta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFecha = new javax.swing.JLabel();
        jLabelSucursal = new javax.swing.JLabel();
        jLabelIdUsuario = new javax.swing.JLabel();
        jLabelNitCliente = new javax.swing.JLabel();
        jTextFieldNitCliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelBuscarCliente = new javax.swing.JPanel();
        jLabelBuscarCliente = new javax.swing.JLabel();
        jPanelBtnGenerarVenta = new javax.swing.JPanel();
        jLabelGenerarVenta = new javax.swing.JLabel();
        jPanelVenta = new javax.swing.JPanel();
        jLabelCodigoPdt = new javax.swing.JLabel();
        jTextFieldCodigoPdt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelBuscarPdt = new javax.swing.JPanel();
        jLabelBuscarPdt = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jPanelAgregarCompra = new javax.swing.JPanel();
        jLabelAgregarCompra = new javax.swing.JLabel();
        jScrollPaneDetalle = new javax.swing.JScrollPane();
        jTableDetalle = new javax.swing.JTable();
        jPanelGuardar = new javax.swing.JPanel();
        jLabelBtnGuardar = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jLabelDescuento = new javax.swing.JLabel();
        JLabelDecDesc = new javax.swing.JLabel();
        jPanelAgregarCli = new javax.swing.JPanel();
        jLabelAgregarCli = new javax.swing.JLabel();
        jPanelCF = new javax.swing.JPanel();
        jLabelCF = new javax.swing.JLabel();
        jLabelNombreCliente = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFecha.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFecha.setText("Fecha: ");
        add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 260, -1));

        jLabelSucursal.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelSucursal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSucursal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSucursal.setText("jLabel2");
        add(jLabelSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 260, -1));

        jLabelIdUsuario.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelIdUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdUsuario.setText("ID: ");
        add(jLabelIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 300, -1));

        jLabelNitCliente.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelNitCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNitCliente.setText("NIT: ");
        add(jLabelNitCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, -1));

        jTextFieldNitCliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNitCliente.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jTextFieldNitCliente.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNitCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNitCliente.setBorder(null);
        jTextFieldNitCliente.setFocusable(false);
        jTextFieldNitCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNitClienteMousePressed(evt);
            }
        });
        jTextFieldNitCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNitClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNitClienteKeyTyped(evt);
            }
        });
        add(jTextFieldNitCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 170, 10));

        jPanelBuscarCliente.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBuscarCliente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuscarCliente.png"))); // NOI18N
        jLabelBuscarCliente.setText("Buscar Cliente");
        jLabelBuscarCliente.setEnabled(false);
        jLabelBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBuscarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBuscarClienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarClienteLayout = new javax.swing.GroupLayout(jPanelBuscarCliente);
        jPanelBuscarCliente.setLayout(jPanelBuscarClienteLayout);
        jPanelBuscarClienteLayout.setHorizontalGroup(
            jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarClienteLayout.createSequentialGroup()
                .addComponent(jLabelBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanelBuscarClienteLayout.setVerticalGroup(
            jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarClienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 160, 30));

        jPanelBtnGenerarVenta.setBackground(new java.awt.Color(94, 96, 98));

        jLabelGenerarVenta.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelGenerarVenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenerarVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Generar.png"))); // NOI18N
        jLabelGenerarVenta.setText("Generar");
        jLabelGenerarVenta.setEnabled(false);
        jLabelGenerarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGenerarVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelGenerarVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelGenerarVentaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnGenerarVentaLayout = new javax.swing.GroupLayout(jPanelBtnGenerarVenta);
        jPanelBtnGenerarVenta.setLayout(jPanelBtnGenerarVentaLayout);
        jPanelBtnGenerarVentaLayout.setHorizontalGroup(
            jPanelBtnGenerarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnGenerarVentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBtnGenerarVentaLayout.setVerticalGroup(
            jPanelBtnGenerarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnGenerarVentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelBtnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 130, 30));

        jPanelVenta.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCodigoPdt.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelCodigoPdt.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodigoPdt.setText("Codigo Producto: ");
        jPanelVenta.add(jLabelCodigoPdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        jTextFieldCodigoPdt.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoPdt.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jTextFieldCodigoPdt.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCodigoPdt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigoPdt.setBorder(null);
        jTextFieldCodigoPdt.setFocusable(false);
        jTextFieldCodigoPdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldCodigoPdtMousePressed(evt);
            }
        });
        jTextFieldCodigoPdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoPdtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoPdtKeyTyped(evt);
            }
        });
        jPanelVenta.add(jTextFieldCodigoPdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 170, 30));
        jPanelVenta.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 170, 10));

        jPanelBuscarPdt.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBuscarPdt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelBuscarPdt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuscarPdt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscarPdt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuscarPdt.png"))); // NOI18N
        jLabelBuscarPdt.setText("Buscar Producto");
        jLabelBuscarPdt.setEnabled(false);
        jLabelBuscarPdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscarPdtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBuscarPdtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBuscarPdtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarPdtLayout = new javax.swing.GroupLayout(jPanelBuscarPdt);
        jPanelBuscarPdt.setLayout(jPanelBuscarPdtLayout);
        jPanelBuscarPdtLayout.setHorizontalGroup(
            jPanelBuscarPdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarPdtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBuscarPdt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBuscarPdtLayout.setVerticalGroup(
            jPanelBuscarPdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarPdtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBuscarPdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelVenta.add(jPanelBuscarPdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 160, 30));

        jSpinnerCantidad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        jSpinnerCantidad.setEnabled(false);
        jPanelVenta.add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 50, 30));

        jPanelAgregarCompra.setBackground(new java.awt.Color(94, 96, 98));

        jLabelAgregarCompra.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelAgregarCompra.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgregarCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar.png"))); // NOI18N
        jLabelAgregarCompra.setText("Agregar");
        jLabelAgregarCompra.setEnabled(false);
        jLabelAgregarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAgregarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAgregarCompraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarCompraLayout = new javax.swing.GroupLayout(jPanelAgregarCompra);
        jPanelAgregarCompra.setLayout(jPanelAgregarCompraLayout);
        jPanelAgregarCompraLayout.setHorizontalGroup(
            jPanelAgregarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarCompraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAgregarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelAgregarCompraLayout.setVerticalGroup(
            jPanelAgregarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarCompraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAgregarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelVenta.add(jPanelAgregarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 130, 30));

        jScrollPaneDetalle.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneDetalle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTableDetalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneDetalle.setViewportView(jTableDetalle);

        jPanelVenta.add(jScrollPaneDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 880, 200));

        jPanelGuardar.setBackground(new java.awt.Color(94, 96, 98));

        jLabelBtnGuardar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuardarCompra.png"))); // NOI18N
        jLabelBtnGuardar.setText("Guardar");
        jLabelBtnGuardar.setEnabled(false);
        jLabelBtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBtnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBtnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelGuardarLayout = new javax.swing.GroupLayout(jPanelGuardar);
        jPanelGuardar.setLayout(jPanelGuardarLayout);
        jPanelGuardarLayout.setHorizontalGroup(
            jPanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelGuardarLayout.setVerticalGroup(
            jPanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelVenta.add(jPanelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 130, 40));

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTotal.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jTextFieldTotal.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldTotal.setText("0.00");
        jTextFieldTotal.setBorder(null);
        jPanelVenta.add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 120, 40));

        jLabelTotal.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTotal.setText("Total: ");
        jPanelVenta.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 80, 40));

        jLabelDescuento.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelDescuento.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescuento.setText("Descuento: ");
        jPanelVenta.add(jLabelDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, 40));

        JLabelDecDesc.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JLabelDecDesc.setForeground(new java.awt.Color(0, 0, 0));
        jPanelVenta.add(JLabelDecDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 80, 40));

        add(jPanelVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 880, 390));

        jPanelAgregarCli.setBackground(new java.awt.Color(94, 96, 98));

        jLabelAgregarCli.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelAgregarCli.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgregarCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AgregarCliente.png"))); // NOI18N
        jLabelAgregarCli.setText("Agregar Cliente");
        jLabelAgregarCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarCliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAgregarCliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAgregarCliMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarCliLayout = new javax.swing.GroupLayout(jPanelAgregarCli);
        jPanelAgregarCli.setLayout(jPanelAgregarCliLayout);
        jPanelAgregarCliLayout.setHorizontalGroup(
            jPanelAgregarCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarCliLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAgregarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelAgregarCliLayout.setVerticalGroup(
            jPanelAgregarCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarCliLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAgregarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelAgregarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 150, 30));

        jPanelCF.setBackground(new java.awt.Color(94, 96, 98));

        jLabelCF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelCF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCF.setText("C/F");
        jLabelCF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCFMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCFLayout = new javax.swing.GroupLayout(jPanelCF);
        jPanelCF.setLayout(jPanelCFLayout);
        jPanelCFLayout.setHorizontalGroup(
            jPanelCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCF, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanelCFLayout.setVerticalGroup(
            jPanelCFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCF, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(jPanelCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 110, 30));

        jLabelNombreCliente.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombreCliente.setText("Cliente:");
        add(jLabelNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 750, -1));
    }// </editor-fold>//GEN-END:initComponents

    /*Metodos que realizan el simulamiento de boton*/

    private void jLabelBuscarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarClienteMouseEntered
        if (this.jLabelBuscarCliente.isEnabled()) {
            this.jPanelBuscarCliente.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelBuscarClienteMouseEntered

    private void jLabelBuscarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarClienteMouseExited
        this.jPanelBuscarCliente.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBuscarClienteMouseExited

    private void jLabelGenerarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGenerarVentaMouseEntered
        if (this.jLabelGenerarVenta.isEnabled()) {
            this.jPanelBtnGenerarVenta.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelGenerarVentaMouseEntered

    private void jLabelGenerarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGenerarVentaMouseExited
        this.jPanelBtnGenerarVenta.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelGenerarVentaMouseExited

    private void jLabelBuscarPdtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarPdtMouseEntered
        if (this.jLabelBuscarPdt.isEnabled()) {
            this.jPanelBuscarPdt.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelBuscarPdtMouseEntered

    private void jLabelBuscarPdtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarPdtMouseExited
        this.jPanelBuscarPdt.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBuscarPdtMouseExited

    private void jLabelAgregarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarCompraMouseEntered
        if (this.jLabelAgregarCompra.isEnabled()) {
            this.jPanelAgregarCompra.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelAgregarCompraMouseEntered

    private void jLabelAgregarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarCompraMouseExited
        this.jPanelAgregarCompra.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelAgregarCompraMouseExited

    private void jLabelBtnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnGuardarMouseEntered
        if (this.jLabelBtnGuardar.isEnabled()) {
            this.jPanelGuardar.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelBtnGuardarMouseEntered

    private void jLabelBtnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnGuardarMouseExited
        this.jPanelGuardar.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelBtnGuardarMouseExited

    private void jLabelAgregarCliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarCliMouseEntered
        this.jPanelAgregarCli.setBackground(new Color(152, 155, 158));
    }//GEN-LAST:event_jLabelAgregarCliMouseEntered

    private void jLabelAgregarCliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarCliMouseExited
        this.jPanelAgregarCli.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelAgregarCliMouseExited

    private void jLabelCFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCFMouseEntered
        if (this.jLabelCF.isEnabled()) {
            this.jPanelCF.setBackground(new Color(152, 155, 158));
        }
    }//GEN-LAST:event_jLabelCFMouseEntered

    private void jLabelCFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCFMouseExited
        this.jPanelCF.setBackground(new Color(94, 96, 98));
    }//GEN-LAST:event_jLabelCFMouseExited

    /*
        Metodos relacionados con 
        el comportamiento del jTextFields NIT
     */

    private void jTextFieldNitClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNitClienteKeyTyped
        if (!(evt.getKeyChar() >= 48 && evt.getKeyChar() <= 57)) { //Valida que solo se ingresen numeros
            evt.consume();
        }
        if (this.jTextFieldNitCliente.getText().length() > 7) { //Valida que sea mayor a 8 digitos
            evt.consume(); //Bloquea la entrada
            Toolkit.getDefaultToolkit().beep(); //Emite un ruido de maximo
        }
    }//GEN-LAST:event_jTextFieldNitClienteKeyTyped

    private void jTextFieldNitClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNitClienteKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) { //Si borra
            if (this.jLabelGenerarVenta.isEnabled()) { //Previene que se genere una venta con un nit incorrecto
                this.jLabelGenerarVenta.setEnabled(false);
                this.jLabelCF.setEnabled(true);
                this.jLabelNombreCliente.setText("Cliente: ");
            }
        }
        if (this.jTextFieldNitCliente.getText().isBlank()) { //Valida si el campo esta vacio
            this.jLabelBuscarCliente.setEnabled(false); //Si lo esta lo desactiva
        } else {
            this.jLabelBuscarCliente.setEnabled(true); //Sino lo vuelve a activar
        }
    }//GEN-LAST:event_jTextFieldNitClienteKeyReleased

    private void jTextFieldNitClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNitClienteMousePressed
        //Deja escribir en el textfield
        this.jTextFieldNitCliente.setFocusable(true);
        this.jTextFieldNitCliente.requestFocus();
    }//GEN-LAST:event_jTextFieldNitClienteMousePressed

    /*
        Eventos con los click de los botones
     */

    private void jLabelBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarClienteMouseClicked
        if (this.jLabelBuscarCliente.isEnabled()) { //Valida que el boton este habilitado
            this.jTextFieldNitCliente.setFocusable(false); //Bloquea temporalmente el jtextfield
            this.jTextFieldNitCliente.requestFocus();
            this.cliente = new Cliente(); //Crea una instancia de cliente
            if (this.cliente.buscarCliente(Integer.valueOf(this.jTextFieldNitCliente.getText()))) { //Valida si existe
                //Setea el label del nombre del cliente
                this.jLabelNombreCliente.setText("Cliente: " + this.cliente.getApellidoCliente() + " " + this.cliente.getNombreCliente());
                //Pone disponible el boton de generar venta
                this.jLabelGenerarVenta.setEnabled(true);
                //Se desactiva la opcion de CF
                this.jLabelCF.setEnabled(false);
            } else {
                this.msg = new ShowMsg(this.frame, true, "Nuevo Cliente detectado, agregalo");
                this.jPanelAgregarCli.setVisible(true); //Habilita la opcion para agregar un cliente
            }
        }
    }//GEN-LAST:event_jLabelBuscarClienteMouseClicked

    private void jLabelCFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCFMouseClicked
        if (this.jLabelCF.isEnabled()) { //Valida que el boton este disponible
            this.jLabelGenerarVenta.setEnabled(true); //Provee la opcion de generar la venta
            this.jLabelBuscarCliente.setEnabled(false); //Desactiva la opcion de buscar
            if (this.jPanelAgregarCli.isVisible()) { //Si esta activa la opcion de agregar la desactiva
                this.jPanelAgregarCli.setVisible(false);
            }
            this.jTextFieldNitCliente.setText("C/F"); //Indica que es CF
            this.jTextFieldNitCliente.setFocusable(false); //Ya no acepta entrada
            this.jTextFieldNitCliente.requestFocus();
            this.jTextFieldNitCliente.setEditable(false); //Desactiva si es editable
        }
    }//GEN-LAST:event_jLabelCFMouseClicked

    private void jLabelAgregarCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarCliMouseClicked
        //Muestra el Jdialog para agregar un cliente
        InsertClientForm form = new InsertClientForm(this.frame, true, Integer.valueOf(this.jTextFieldNitCliente.getText()));
        this.cliente = new Cliente(); //Crea una nueva instancia de cliente
        if (this.cliente.buscarCliente(Integer.valueOf(this.jTextFieldNitCliente.getText()))) { //Busca el cliente recien ingresado y setea valores
            this.jLabelNombreCliente.setText("Cliente: " + this.cliente.getApellidoCliente() + " " + this.cliente.getNombreCliente());
            this.jLabelCF.setEnabled(false);
            this.jLabelGenerarVenta.setEnabled(true);
        }
        this.jPanelAgregarCli.setVisible(false); //Hace invisible el panel
    }//GEN-LAST:event_jLabelAgregarCliMouseClicked

    private void jLabelGenerarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGenerarVentaMouseClicked
        if (this.jLabelGenerarVenta.isEnabled()) {
            this.jLabelGenerarVenta.setEnabled(false);
            if (this.jLabelBuscarCliente.isEnabled()) {
                this.jLabelBuscarCliente.setEnabled(false);
                this.venta = new Venta(Conversor.determinarSucursal(this.jLabelSucursal.getText()), this.date, EmpLogueado.empleadoLogueado.getIdUsuario(),
                        String.valueOf(this.cliente.getNitCliente()), false, 0.00);
                this.JLabelDecDesc.setText(String.valueOf(Conversor.retornarDescuento(this.venta.buscarUltimaCompra(this.cliente.getNitCliente()))));
            } else if (this.jLabelCF.isEnabled()) {
                this.jLabelCF.setEnabled(false);
                this.jLabelNombreCliente.setText("Cliente: Anonimo");
                this.venta = new Venta(Conversor.determinarSucursal(this.jLabelSucursal.getText()), this.date, EmpLogueado.empleadoLogueado.getIdUsuario(),
                        null, true, 0.00);
                this.JLabelDecDesc.setText("0.00");
            }
            LlenadorTabla.cambiarEncabezado(jTableDetalle, new String[]{"Codigo Producto", "Descripcion", "Cantidad", "Sub-Total"});
            this.jPanelVenta.setVisible(true);
        }
    }//GEN-LAST:event_jLabelGenerarVentaMouseClicked

    /*
        Metodos relacionados con el 
        comportamiento de textField de buscar producto
     */

    private void jTextFieldCodigoPdtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPdtKeyTyped
        if (this.jTextFieldCodigoPdt.getText().length() > 11) { //Valida que no se pase de la cantidad maxima de caracteres
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldCodigoPdtKeyTyped

    private void jTextFieldCodigoPdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPdtKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if (this.jLabelAgregarCompra.isEnabled()) {
                this.jLabelAgregarCompra.setEnabled(false);
                this.jSpinnerCantidad.setEnabled(false);
                this.jSpinnerCantidad.setValue(1);
            }
        }
        if (this.jTextFieldCodigoPdt.getText().isBlank()) { //Valida si el campo esta vacio
            this.jLabelBuscarPdt.setEnabled(false); //Si lo esta lo desactiva
        } else {
            this.jLabelBuscarPdt.setEnabled(true); //Sino lo vuelve a activar
        }
    }//GEN-LAST:event_jTextFieldCodigoPdtKeyReleased

    private void jTextFieldCodigoPdtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPdtMousePressed
        this.jTextFieldCodigoPdt.setFocusable(true);
        this.jTextFieldCodigoPdt.requestFocus();
    }//GEN-LAST:event_jTextFieldCodigoPdtMousePressed

    /*
        Otros eventos de click
     */

    private void jLabelBuscarPdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarPdtMouseClicked
        if (this.jLabelBuscarPdt.isEnabled()) { //Si esta disponible el boton buscar pdt
            this.product = new Producto(); //Crea un nuevo producto
            if (this.product.buscarProducto(this.jTextFieldCodigoPdt.getText(), Conversor.determinarSucursal(this.jLabelSucursal.getText()))) {
                if (this.product.getCantidad() != 0) {
                    SpinnerNumberModel modelo = (SpinnerNumberModel) this.jSpinnerCantidad.getModel();
                    modelo.setMaximum(this.product.getCantidad());
                    this.jSpinnerCantidad.setEnabled(true);
                    this.jLabelAgregarCompra.setEnabled(true);
                } else {
                    this.msg = new ShowMsg(this.frame, true, "Ya no tenemos existencias de este producto por el momento");
                }
            }
        }
    }//GEN-LAST:event_jLabelBuscarPdtMouseClicked

    private void jLabelAgregarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarCompraMouseClicked
        if (this.jLabelAgregarCompra.isEnabled()) {
            String codigoPDTA = this.product.getCodigoProducto();
            int cantidadPDTA = this.product.getCantidad();
            int cantidad = (Integer) this.jSpinnerCantidad.getValue();
            int existe = LlenadorTabla.verificarCompra(jTableDetalle, codigoPDTA, cantidadPDTA, cantidad);
            if (existe == 0) {
                Lista lista = new Lista(null);
                lista.agregarNodo(this.jTextFieldCodigoPdt.getText());
                lista.agregarNodo(this.product.getDescripcionProducto());
                lista.agregarNodo(this.jSpinnerCantidad.getValue());
                lista.agregarNodo(this.product.getPrecioUnitario() * Double.valueOf(this.jSpinnerCantidad.getValue() + ""));
                LlenadorTabla.llenarTabla(jTableDetalle, lista);

            } else if (existe == 2) {
                this.msg = new ShowMsg(this.frame, true, "La cantidad que deseas comprar supera al stock en esta tienda");
            }
            this.jLabelAgregarCompra.setEnabled(false);
            this.jSpinnerCantidad.setValue(1);
            this.jSpinnerCantidad.setEnabled(false);
            double total = Conversor.calcularTotal(jTableDetalle, this.JLabelDecDesc.getText());
            this.jTextFieldTotal.setText(String.valueOf(total));
            this.venta.setTotal(total);
            if (!this.jLabelBtnGuardar.isEnabled()) {
                this.jLabelBtnGuardar.setEnabled(true);
            }

        }
    }//GEN-LAST:event_jLabelAgregarCompraMouseClicked

    private void jLabelBtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnGuardarMouseClicked
        if (this.jLabelBtnGuardar.isEnabled()) { //Valida si el boton guardar ya esta disponible
            if (this.venta.insertarCompra()) { //Valida si la compra fue realizada con exito
                Conversor.insertarDetalles(jTableDetalle, this.venta.buscarUltimaInsercion(), Conversor.determinarSucursal(this.jLabelSucursal.getText()));
                VentaR pnl = (VentaR) SwingUtilities.getWindowAncestor(this); //SE vuelve a actualizar el panel
                this.msg = new ShowMsg(this.frame, true, "Venta Exitosa");
                pnl.repintarPanelVenta();
            } else {
                this.msg = new ShowMsg(this.frame, true, "Alguio salio mal en la venta");
            }
        }
    }//GEN-LAST:event_jLabelBtnGuardarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelDecDesc;
    private javax.swing.JLabel jLabelAgregarCli;
    private javax.swing.JLabel jLabelAgregarCompra;
    private javax.swing.JLabel jLabelBtnGuardar;
    private javax.swing.JLabel jLabelBuscarCliente;
    private javax.swing.JLabel jLabelBuscarPdt;
    private javax.swing.JLabel jLabelCF;
    private javax.swing.JLabel jLabelCodigoPdt;
    private javax.swing.JLabel jLabelDescuento;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelGenerarVenta;
    private javax.swing.JLabel jLabelIdUsuario;
    private javax.swing.JLabel jLabelNitCliente;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelAgregarCli;
    private javax.swing.JPanel jPanelAgregarCompra;
    private javax.swing.JPanel jPanelBtnGenerarVenta;
    private javax.swing.JPanel jPanelBuscarCliente;
    private javax.swing.JPanel jPanelBuscarPdt;
    private javax.swing.JPanel jPanelCF;
    private javax.swing.JPanel jPanelGuardar;
    private javax.swing.JPanel jPanelVenta;
    private javax.swing.JScrollPane jScrollPaneDetalle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTableDetalle;
    private javax.swing.JTextField jTextFieldCodigoPdt;
    private javax.swing.JTextField jTextFieldNitCliente;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables

}
